export type Publication = {
  /** Unique id. Blog posts can reference this via the `publication` frontmatter field. */
  id: string
  title: string
  category: string
  summary: string
  date: string
  format: string
  fileUrl: string
  tags: string[]
  /** Original author(s), for publications not authored by Herufi. */
  author?: string
  /** Originating institution, for curated third party research. */
  source?: string
}

// Publications are the detailed, long form reports behind the blog posts.
// Rendered as real Next.js routes at app/publications/[slug]/page.tsx, with
// figures generated by scripts/generate_charts.py into data/charts/*.json.
export const publications: Publication[] = [
  {
    id: 'broken-ladder-2014-baseline',
    title: 'The Broken Ladder',
    category: 'Baseline Diagnosis',
    summary: 'A global baseline diagnosis of African startup investment. Evidence from 49,436 companies, data to 2014.',
    date: '2026',
    format: 'HTML',
    fileUrl: '/publications/broken-ladder-2014-baseline',
    tags: ['Venture Capital', 'Africa', 'Startup Funding', 'Baseline'],
  },
  {
    id: 'frontier-to-market-2014-2026',
    title: 'From Frontier to Market',
    category: 'Reality Check',
    summary: 'How African startup funding transformed between 2014 and 2026. A source linked reality check of the 2014 lessons.',
    date: '2026',
    format: 'HTML',
    fileUrl: '/publications/frontier-to-market-2014-2026',
    tags: ['Venture Capital', 'Africa', 'Capital Structure', 'Retrospective'],
  },
  {
    id: 'continent-heading-2026-2030',
    title: 'Where the Continent Is Heading',
    category: 'Scenarios',
    summary: 'Validated scenarios for African startup funding, 2026 to 2030. Every variable, every assumption, every check.',
    date: '2026',
    format: 'HTML',
    fileUrl: '/publications/continent-heading-2026-2030',
    tags: ['Venture Capital', 'Africa', 'Forecasting', 'Scenarios'],
  },
  {
    id: 'writing-the-cheques-2026',
    title: 'Who Is Actually Writing the Cheques',
    category: 'Capital Supply and Portfolio Construction',
    summary: "African VC's capital supply layer, mapped and turned into a validated Monte Carlo portfolio model. Report 4 of the African Startup Investment series.",
    date: '2026',
    format: 'HTML',
    fileUrl: '/publications/writing-the-cheques-2026',
    tags: ['Venture Capital', 'Africa', 'LP Capital', 'Portfolio Construction'],
  },
  {
    id: 'filling-the-missing-middle-2026',
    title: 'Filling the Missing Middle',
    category: 'Instruments and Return Math',
    summary: "Return math for Africa's Series A and B gap. Four financing mechanisms already active on the continent, priced instrument by instrument and sized against the gap. Report 5 of the African Startup Investment series.",
    date: '2026',
    format: 'HTML',
    fileUrl: '/publications/filling-the-missing-middle-2026',
    tags: ['Venture Capital', 'Africa', 'Venture Debt', 'Blended Finance'],
  },
  {
    id: 'gvc-firm-participation-kenya-2022',
    title: 'Firm Level Analysis of Global Value Chain Participation in Kenya',
    category: 'Global Value Chains',
    summary: 'A firm level study of 358 Kenyan enterprises finds a global value chain participation index of just 18.65 per cent, driven by firm size, productivity, research and development, and access to finance.',
    date: '2022',
    format: 'PDF',
    fileUrl: '/publications/gvc-firm-participation-kenya-2022.pdf',
    tags: ['Trade', 'Kenya', 'SMEs', 'Global Value Chains'],
    author: 'Kevin Wanjala and Mohamed Omar Abdullahi',
    source: 'Kenya Institute for Public Policy Research and Analysis (KIPPRA), Discussion Paper No. 285',
  },
  {
    id: 'sme-gvc-financial-interventions-2022-23',
    title: 'Integrating Small and Medium Enterprises into Global Value Chain through Financial Interventions',
    category: 'Policy Brief',
    summary: 'Only 15 per cent of Kenyan SMEs engage in global value chains, mostly because of financial constraints. This brief sets out six financing interventions that could close the gap.',
    date: '2022/2023',
    format: 'PDF',
    fileUrl: '/publications/sme-gvc-financial-interventions-2022-23.pdf',
    tags: ['Trade', 'Kenya', 'SMEs', 'Access to Finance'],
    author: 'Kevin Wafula and Mohamed Abdulahi',
    source: 'Kenya Institute for Public Policy Research and Analysis (KIPPRA), Policy Brief No. 19/2022-2023',
  },
  {
    id: 'export-levies-hides-skins-leather-2024',
    title: "Effect of Export Levies on Hides and Skins on Competitiveness of Kenya's Leather Products",
    category: 'Trade Policy',
    summary: "Testing four export levy regimes on raw hides and skins against Kenya's leather export competitiveness, this paper finds higher levies broadened market reach but argues value addition needs support across the whole value chain.",
    date: '2024',
    format: 'PDF',
    fileUrl: '/publications/export-levies-hides-skins-leather-2024.pdf',
    tags: ['Trade', 'Kenya', 'Leather Industry', 'Export Policy'],
    author: 'Mohamed Ramadhan, Kenneth Malot, Kevin Wanjala and John Karanja',
    source: 'Kenya Institute for Public Policy Research and Analysis (KIPPRA), Discussion Paper No. 360',
  },
]
